name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        build_type: [release, debug]
        channel: [1.82.0]

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      shell: bash
      run: sudo apt install libsdl2-dev libsdl2-ttf-dev libsdl2-gfx-dev

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        if [ "${{matrix.build_type}}" = "release" ]
        then
          echo "cargo-options=--verbose --release" >> "$GITHUB_OUTPUT"
        else
          echo "cargo-options=--verbose" >> "$GITHUB_OUTPUT"
        fi

    - name: Set channel
      run: |
        rustup update
        rustup default ${{matrix.channel}}

    - name: Install cargo extensions
      shell: bash
      run: cargo install cargo-fuzz

    - name: Build (lib)
      run: cargo build --package bugs-lib ${{steps.strings.outputs.cargo-options}}
    - name: Run tests (lib)
      run: cargo test --package bugs-lib ${{steps.strings.outputs.cargo-options}}
    - name: Run benches (lib)
      if: matrix.build_type == 'release'
      run: cargo bench --package bugs-lib --verbose

    - name: Build (simulator)
      run: cargo build --package bugs-simulator ${{steps.strings.outputs.cargo-options}}
    - name: Run tests (simulator)
      run: cargo test  --package bugs-simulator ${{steps.strings.outputs.cargo-options}}
    - name: Run benches (simulator)
      if: matrix.build_type == 'release'
      run: cargo bench --package bugs-simulator --verbose

    - name: Build (app)
      run: cargo build ${{steps.strings.outputs.cargo-options}}
    - name: Run tests (app)
      run: cargo test ${{steps.strings.outputs.cargo-options}}
    - name: Run benches (app)
      if: matrix.build_type == 'release'
      run: cargo bench --verbose
    - name: Build fuzzer (app)
      run: |
        rustup default nightly
        cargo fuzz build ${{steps.strings.outputs.cargo-options}}

  check-format:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Rust format
      run: cargo fmt --
    - name: Suggest format changes
      uses: reviewdog/action-suggester@v1
      with:
        tool_name: formatters
        level: error
        fail_level: any
